name: Update Holiday

on:
  schedule:
    - cron: '01 14 * * *' # Запуск каждый день в 01:00 UTC (4:00 МСК)
  workflow_dispatch: # Кнопка для ручного запуска

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Скачиваем репозиторий
      uses: actions/checkout@v3

    - name: Устанавливаем Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Устанавливаем библиотеки
      run: pip install requests beautifulsoup4

    - name: Запускаем парсер
      run: python parser.py

    - name: Сохраняем изменения (git push)
      run: |
        git config --global user.name 'HolidayBot'
        git config --global user.email 'bot@noreply.github.com'
        git add data.json
        # Если изменений нет (файл тот же), commit не упадет с ошибкой
        git commit -m "Обновлены праздники" || echo "Изменений нет"
        git push