name: Update Holiday

on:
  schedule:
    - cron: '01 14 * * *' # Запуск каждый день в 01:00 UTC (4:00 МСК)
  workflow_dispatch: # Кнопка для ручного запуска

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Скачиваем репозиторий
      uses: actions/checkout@v3

    - name: Устанавливаем Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Устанавливаем зависимости (Puppeteer)
      run: npm install

    - name: Запускаем парсер
      run: node parser.js

    - name: Сохраняем результат (git push)
      run: |
        git config --global user.name 'HolidayBot'
        git config --global user.email 'bot@noreply.github.com'
        git add data.json
        git commit -m "Обновление праздников" || echo "Изменений нет"
        git push

    - name: Загрузить скриншот (для отладки)
      if: always() # Выполнять даже если были ошибки
      uses: actions/upload-artifact@v4
      with:
        name: debug-screenshot
        path: debug-screenshot.png